name: Check Selenoid Setup Action

on: [push]

jobs:
  setup-selenoid:
    runs-on: ubuntu-latest
    name: Test Setup Selenoid
    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      TEST_PROJECT: automationpractice-github-actions-demo

    steps:
        - name: Set up Node.js 14
          uses: actions/setup-node@v2-beta
          with:
            node-version: 14

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Set up Selenoid
          uses: isandratskiy/selenoid-action@v0.3.0
          with:
            chrome_version: "90.0"
            firefox_version: "87.0"

        - name: Checkout UI Tests
          uses: actions/checkout@v2
          with:
            repository: isandratskiy/${{ env.TEST_PROJECT }}
            path: ${{ env.TEST_PROJECT }}

        - name: Run UI Tests
          run: |
            cd $TEST_PROJECT
            ./gradlew -Pthread=2 -Plaunch=remote testChrome
            ./gradlew -Pthread=2 -Plaunch=remote testFirefox
