on: [push]

jobs:
  setup-selenoid:
    runs-on: ubuntu-latest
    name: Test Setup Selenoid
    env:
      TEST_PROJECT: webdriverio5-typescript-draft

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Node.js 14
          uses: actions/setup-node@v2-beta
          with:
            node-version: 14

        - name: Set up Selenoid
          uses: isandratskiy/selenoid-action@v0.1.8
          with:
            chrome_version: "90.0"
            firefox_version: "87.0"

        - name: Checkout k6 tests
          uses: actions/checkout@v2
          with:
            repository: isandratskiy/${{ env.TEST_PROJECT }}
            path: ${{ env.TEST_PROJECT }}

        - name: Run UI Tests
          env:
            SELENOID: '127.0.0.1'
          run: |
            cd $TEST_PROJECT
            npm cit

        - name: Check
          if: always()
          run: |
            ls
            docker ps
            ./cm version
